/** Legacy Figma design routes → production SuperAdmin portal routes. */
export const SUPERADMIN_FIGMA_REDIRECTS: Record<string, string> = {
  "/": "/portal/login",
  "/splash-screen": "/portal/login",
  "/administrator-pin": "/portal/login",
  "/recover-administrator-pin": "/portal/recover-admin",
  "/email-recovery-confirmation": "/portal/email-confirmation",
  "/super-admin-dashboadr-section": "/portal/dashboard",
  "/super-admin-device-management": "/portal/users",
  "/super-admin-key": "/portal/keys",
  "/super-admin-logs": "/portal/logs",
  "/super-admin-cloud": "/portal/cloud",
  "/super-admin-help": "/portal/help",
  "/super-admin-settings": "/portal/settings",
  "/super-admin-settings-1364-2741": "/portal/settings",
  "/super-admin-settings-1438-3780": "/portal/settings",
  "/super-admin-account-setting": "/portal/settings",
  "/super-admin-registration-1": "/portal/admins",
  "/administrators-registration-2": "/portal/admins",
  "/register-user": "/portal/admins",
  "/edit-user": "/portal/admins",
  "/register-admin": "/portal/admins",
  "/edit-admin": "/portal/admins",
  "/backup-management": "/portal/settings",
  "/restore-admin": "/portal/recycle-bin",
  "/restore-user": "/portal/recycle-bin",
  "/delete-device": "/portal/users",
  "/delete-device-1490-866": "/portal/users",
  "/delete-device-1752-889": "/portal/users",
  "/revoke-key": "/portal/keys",
  "/reject-cloud": "/portal/cloud",
  "/reject-cloud-1709-961": "/portal/cloud",
  "/reject-cloud-1709-1009": "/portal/cloud",
  "/reject-cloud-1709-993": "/portal/cloud",
  "/reject-cloud-1709-977": "/portal/cloud",
  "/reject-cloud-1698-2119": "/portal/cloud",
  "/reject-cloud-1709-1036": "/portal/cloud",
  "/reject-cloud-1709-1069": "/portal/cloud",
  "/reject-cloud-1709-1058": "/portal/cloud",
  "/reject-cloud-1709-1047": "/portal/cloud",
  "/user-verification": "/portal/users",
  "/reports-filter": "/portal/help",
  "/troubleshooting-filter": "/portal/help",
};

export function resolveSuperAdminFigmaRedirect(pathname: string): string | null {
  return SUPERADMIN_FIGMA_REDIRECTS[pathname] ?? null;
}
