"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const electron_1 = require("electron");
electron_1.contextBridge.exposeInMainWorld("bukolabs", {
    auth: {
        login: (payload) => electron_1.ipcRenderer.invoke("auth:login", payload),
        logout: (payload) => electron_1.ipcRenderer.invoke("auth:logout", payload),
        activateKey: (payload) => electron_1.ipcRenderer.invoke("auth:activate-key", payload),
        checkSession: (payload) => electron_1.ipcRenderer.invoke("auth:check-session", payload),
        requestRecovery: (payload) => electron_1.ipcRenderer.invoke("auth:request-recovery", payload),
        getProfile: (payload) => electron_1.ipcRenderer.invoke("auth:get-profile", payload),
        updateProfile: (payload) => electron_1.ipcRenderer.invoke("auth:update-profile", payload),
        changePassword: (payload) => electron_1.ipcRenderer.invoke("auth:change-password", payload),
        getSupportContact: (payload) => electron_1.ipcRenderer.invoke("auth:get-support-contact", payload),
        syncPendingActivations: () => electron_1.ipcRenderer.invoke("auth:sync-pending-activations"),
    },
    keys: {
        validate: (payload) => electron_1.ipcRenderer.invoke("keys:validate", payload),
        getStatus: (payload) => electron_1.ipcRenderer.invoke("keys:get-status", payload ?? {}),
        requestExtension: (payload) => electron_1.ipcRenderer.invoke("keys:request-extension", payload),
        requestRenewal: (payload) => electron_1.ipcRenderer.invoke("keys:request-renewal", payload),
    },
    scanner: {
        listDevices: () => electron_1.ipcRenderer.invoke("scanner:list-devices"),
        getCapabilities: (deviceId) => electron_1.ipcRenderer.invoke("scanner:get-capabilities", { deviceId }),
        startScan: (payload) => electron_1.ipcRenderer.invoke("scanner:start-scan", payload),
        cancelScan: () => electron_1.ipcRenderer.invoke("scanner:cancel-scan"),
    },
    devices: {
        register: (payload) => electron_1.ipcRenderer.invoke("devices:register", payload),
        syncForUser: (payload) => electron_1.ipcRenderer.invoke("devices:sync-for-user", payload),
    },
    files: {
        save: (payload) => electron_1.ipcRenderer.invoke("files:save", payload),
        list: (payload) => electron_1.ipcRenderer.invoke("files:list", payload),
        delete: (payload) => electron_1.ipcRenderer.invoke("files:delete", payload),
        restore: (payload) => electron_1.ipcRenderer.invoke("files:restore", payload),
        search: (payload) => electron_1.ipcRenderer.invoke("files:search", payload),
        getOcrStatus: (payload) => electron_1.ipcRenderer.invoke("files:get-ocr-status", payload),
        extractOcrFromPath: (payload) => electron_1.ipcRenderer.invoke("files:extract-ocr-from-path", payload),
    },
    print: {
        listPrinters: (payload) => electron_1.ipcRenderer.invoke("print:list-printers", payload),
        start: (payload) => electron_1.ipcRenderer.invoke("print:start", payload),
    },
    sync: {
        trigger: () => electron_1.ipcRenderer.invoke("sync:trigger"),
        status: () => electron_1.ipcRenderer.invoke("sync:status"),
    },
    help: {
        submitConcern: (payload) => electron_1.ipcRenderer.invoke("help:submit-concern", payload),
        listTickets: (payload) => electron_1.ipcRenderer.invoke("help:list-tickets", payload),
        markReplyRead: (payload) => electron_1.ipcRenderer.invoke("help:mark-reply-read", payload),
    },
    gateway: {
        getConfig: () => electron_1.ipcRenderer.invoke("gateway:get-config"),
        setUrl: (payload) => electron_1.ipcRenderer.invoke("gateway:set-url", payload),
        checkAvailable: () => electron_1.ipcRenderer.invoke("gateway:check-available"),
    },
    filesystem: {
        getQuickLocations: () => electron_1.ipcRenderer.invoke("fs:get-quick-locations"),
        listDirectories: (payload) => electron_1.ipcRenderer.invoke("fs:list-directories", payload),
        listContents: (payload) => electron_1.ipcRenderer.invoke("fs:list-contents", payload),
        pickFolder: (payload) => electron_1.ipcRenderer.invoke("fs:pick-folder", payload),
        pickDocument: (payload) => electron_1.ipcRenderer.invoke("fs:pick-document", payload),
        pickImage: (payload) => electron_1.ipcRenderer.invoke("fs:pick-image", payload),
        showItemInFolder: (payload) => electron_1.ipcRenderer.invoke("fs:show-item-in-folder", payload),
        openPath: (payload) => electron_1.ipcRenderer.invoke("fs:open-path", payload),
        openInWord: (payload) => electron_1.ipcRenderer.invoke("fs:open-in-word", payload),
        validateDirectory: (payload) => electron_1.ipcRenderer.invoke("fs:validate-directory", payload),
        ensureDirectory: (payload) => electron_1.ipcRenderer.invoke("fs:ensure-directory", payload),
        getDefaultStorageRoot: () => electron_1.ipcRenderer.invoke("fs:get-default-storage-root"),
        ensureDefaultStorageRoot: () => electron_1.ipcRenderer.invoke("fs:ensure-default-storage-root"),
        importDocumentToFolder: (payload) => electron_1.ipcRenderer.invoke("fs:import-document-to-folder", payload),
        resolveUniqueFilePath: (payload) => electron_1.ipcRenderer.invoke("fs:resolve-unique-file-path", payload),
        listDocumentsInFolder: (payload) => electron_1.ipcRenderer.invoke("fs:list-documents-in-folder", payload),
        renamePath: (payload) => electron_1.ipcRenderer.invoke("fs:rename-path", payload),
        deletePath: (payload) => electron_1.ipcRenderer.invoke("fs:delete-path", payload),
        copyPathToClipboard: (payload) => electron_1.ipcRenderer.invoke("fs:copy-path-to-clipboard", payload),
        openFolder: (payload) => electron_1.ipcRenderer.invoke("fs:open-folder", payload),
        moveToRecycleBin: (payload) => electron_1.ipcRenderer.invoke("fs:move-to-recycle-bin", payload),
        restoreFromRecycleBin: (payload) => electron_1.ipcRenderer.invoke("fs:restore-from-recycle-bin", payload),
    },
});
