param(
  [string]$HostName = "localhost",
  [int]$Port = 5432,
  [string]$User = "postgres",
  [string]$Password,
  [string]$Database = "bukolabs_offline",
  [switch]$Seed,
  [switch]$Reset
)

$ErrorActionPreference = "Stop"

$psqlCandidates = @(
  "C:\Program Files\PostgreSQL\18\bin\psql.exe",
  "C:\Program Files\PostgreSQL\17\bin\psql.exe",
  "C:\Program Files\PostgreSQL\16\bin\psql.exe"
)

$psqlExe = $psqlCandidates | Where-Object { Test-Path $_ } | Select-Object -First 1
if (-not $psqlExe) {
  throw "psql.exe not found. Install PostgreSQL or add psql to PATH."
}

$repoRoot = Split-Path $PSScriptRoot -Parent
$migrationFile = Join-Path $repoRoot "backend-modules\shared\migrations\offline\001_initial_schema.postgres.sql"
$seedFile = Join-Path $repoRoot "backend-modules\shared\migrations\offline\002_seed_roles.postgres.sql"
$envFile = Join-Path $repoRoot "backend-modules\shared\.env.offline"

if (-not (Test-Path $migrationFile)) {
  throw "Migration file not found: $migrationFile"
}

if (-not $Password) {
  Write-Host "Enter the PostgreSQL password for user '$User'."
  Write-Host "(Usually the same password as your online bukolabs_online database.)"
  $secure = Read-Host "Password" -AsSecureString
  $Password = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
  )
}

function Invoke-Psql {
  param(
    [string]$Sql,
    [string]$DatabaseName = "postgres"
  )

  $env:PGPASSWORD = $Password
  $previousErrorAction = $ErrorActionPreference
  $ErrorActionPreference = "Continue"

  try {
    $rawOutput = $Sql | & $psqlExe -h $HostName -p $Port -U $User -d $DatabaseName -v ON_ERROR_STOP=1 2>&1
    $lines = @($rawOutput | ForEach-Object { "$_" })

    if ($LASTEXITCODE -ne 0) {
      throw ($lines -join "`n")
    }

    foreach ($line in $lines) {
      if ($line -match '^\s*NOTICE:') {
        Write-Host $line -ForegroundColor DarkYellow
      }
    }

    return ($lines -join "`n")
  } finally {
    $ErrorActionPreference = $previousErrorAction
  }
}

Write-Host "Creating database '$Database' if needed..."
if ($Reset) {
  Write-Host "Reset requested - dropping database '$Database'..." -ForegroundColor Yellow
  $dropSql = 'DROP DATABASE IF EXISTS ' + $Database + ' WITH (FORCE);'
  Invoke-Psql -Sql $dropSql -DatabaseName 'postgres' | Out-Null
}

try {
  $createSql = 'CREATE DATABASE ' + $Database + ';'
  Invoke-Psql -Sql $createSql -DatabaseName 'postgres' | Out-Null
} catch {
  if ($_.Exception.Message -notmatch 'already exists') {
    throw
  }
}

Write-Host "Running offline schema migration..."
$migrationSql = Get-Content $migrationFile -Raw
try {
  Invoke-Psql -Sql $migrationSql -DatabaseName $Database | Out-Null
} catch {
  Write-Host ""
  Write-Host "Migration failed. Re-run with -Reset to drop and recreate:" -ForegroundColor Yellow
  Write-Host "  npm run setup:postgres-offline:reset" -ForegroundColor Cyan
  throw
}

if ($Seed -and (Test-Path $seedFile)) {
  Write-Host "Seeding offline roles..."
  $seedSql = Get-Content $seedFile -Raw
  Invoke-Psql -Sql $seedSql -DatabaseName $Database | Out-Null
}

Write-Host "Verifying tables..."
$checkSql = "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' ORDER BY table_name;"
$tableList = Invoke-Psql -Sql $checkSql -DatabaseName $Database

$requiredTables = @(
  "roles", "users", "serial_keys", "devices", "folders", "documents",
  "scan_history", "activity_logs", "cloud_sync"
)

foreach ($table in $requiredTables) {
  if ($tableList -notmatch $table) {
    throw "Missing table after migration: $table"
  }
}

$encodedPassword = [uri]::EscapeDataString($Password)
$databaseUrl = "postgresql://${User}:$encodedPassword@${HostName}:$Port/$Database"

$envContent = @(
  "# Offline PostgreSQL - generated by scripts/setup-postgres-offline.ps1"
  ""
  "OFFLINE_DATABASE_URL=$databaseUrl"
  "OFFLINE_DB_HOST=$HostName"
  "OFFLINE_DB_PORT=$Port"
  "OFFLINE_DB_USER=$User"
  "OFFLINE_DB_PASSWORD=$Password"
  "OFFLINE_DB_NAME=$Database"
  ""
)

$envContent | Set-Content $envFile -Encoding UTF8

Write-Host ""
Write-Host "PostgreSQL offline database setup complete." -ForegroundColor Green
Write-Host "Database: $Database"
Write-Host "Env file: $envFile"
Write-Host ""
Write-Host "Test with: npm run test:postgres-offline"
